
name: Docker Image

on: push

jobs: 
  build: 
    runs-on: linux/arm64
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: docker build . --platform=linux/arm64 -t learn-ci-cd  -f Dockerfile
      - name: Run
        run: docker run -it --init learn-ci-cd  /bin/bash