
name: Docker Image

on: [push]

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: docker build . --platform=linux/amd64 -t learn-ci-cd
      - name: Run
        run: docker run -it --init learn-ci-cd